name: Update HTML File Every 1 Hour

on:
  # Run automatically every 1 hour
  schedule:
    - cron: '0 */1 * * *'  # Run every 1 hour (cron syntax: minute hour day month day-of-week)

  # Manual trigger
  workflow_dispatch:

jobs:
  update-html:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GPD }}  # Use your custom token name here

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Step 3: Install dependencies from requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run the Python script to generate HTML
      - name: Run Python script to generate HTML
        run: |
          python generate_html.py

      # Step 5: Commit and push changes (if there are any)
      - name: Commit and push changes
        env:
          GPD: ${{ secrets.GPD }}  # Use your custom token name here
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

          # Check if there are changes to commit
          if [[ -n $(git status --porcelain) ]]; then
            git add index.html
            git commit -m "Auto-generated HTML file at $(date)"
            git push https://x-access-token:${GPD}@github.com/${{ github.repository }}.git main
          else
            echo "No changes to commit."
          fi
